language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis

script:
  - tox

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    branch: master
    python: '3.6'
